# Generated by Django 5.0.6 on 2025-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('factory_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('ship_name', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
