# Generated by Django 5.0.6 on 2025-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_by_name', models.CharField(max_length=255)),
                ('recipient_email', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('shipper', models.CharField(max_length=255)),
                ('shipper_freight_number', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=255)),
                ('shipment_type', models.CharField(choices=[('air_freight', 'Air Freight'), ('sea_freight', 'Sea Freight'), ('rail_freight', 'Rail Freight'), ('post', 'Post')], max_length=20)),
                ('carrier_company', models.CharField(max_length=255)),
                ('carrier_tracking_number', models.CharField(max_length=100)),
                ('carrier_bl_number', models.CharField(max_length=100)),
                ('vessel_flight_name', models.CharField(max_length=255)),
                ('loading_date', models.DateField()),
                ('loading_location', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('port_airport_departure', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('port_airport_arrival', models.CharField(max_length=255)),
                ('packaging_type', models.CharField(choices=[('pallet', 'Pallet'), ('cartons', 'Cartons'), ('pieces', 'Pieces')], max_length=20)),
                ('total_packages', models.IntegerField()),
                ('freight_terms', models.CharField(choices=[('exw', 'EXW'), ('fob', 'FOB'), ('cif', 'CIF'), ('cfr', 'CFR'), ('dap', 'DAP')], max_length=10)),
                ('includes_container', models.BooleanField(default=False)),
                ('number_of_containers', models.IntegerField(default=0)),
                ('container_1_number', models.CharField(blank=True, max_length=100)),
                ('container_2_number', models.CharField(blank=True, max_length=100)),
                ('container_3_number', models.CharField(blank=True, max_length=100)),
                ('container_4_number', models.CharField(blank=True, max_length=100)),
                ('container_5_number', models.CharField(blank=True, max_length=100)),
                ('logistics_status', models.CharField(choices=[('preparing', 'Preparing'), ('shipping', 'Shipping'), ('arrived', 'Arrived'), ('complete', 'Complete')], default='preparing', max_length=20)),
                ('other_remarks', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
