# Generated by Django 5.0.6 on 2025-08-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('shipping', 'Shipping'), ('arrived', 'Arrived'), ('complete', 'Complete')], default='preparing', max_length=20),
        ),
    ]
